// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ianhecker/eth-gas-watcher/internal/endpoint/feehistory"
	"github.com/ianhecker/eth-gas-watcher/internal/endpoint/payload"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEndpointInterface creates a new instance of MockEndpointInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEndpointInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEndpointInterface {
	mock := &MockEndpointInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEndpointInterface is an autogenerated mock type for the EndpointInterface type
type MockEndpointInterface struct {
	mock.Mock
}

type MockEndpointInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEndpointInterface) EXPECT() *MockEndpointInterface_Expecter {
	return &MockEndpointInterface_Expecter{mock: &_m.Mock}
}

// GetFeeHistory provides a mock function for the type MockEndpointInterface
func (_mock *MockEndpointInterface) GetFeeHistory(payload1 payload.Payload) (*feehistory.Result, error) {
	ret := _mock.Called(payload1)

	if len(ret) == 0 {
		panic("no return value specified for GetFeeHistory")
	}

	var r0 *feehistory.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(payload.Payload) (*feehistory.Result, error)); ok {
		return returnFunc(payload1)
	}
	if returnFunc, ok := ret.Get(0).(func(payload.Payload) *feehistory.Result); ok {
		r0 = returnFunc(payload1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feehistory.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(payload.Payload) error); ok {
		r1 = returnFunc(payload1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEndpointInterface_GetFeeHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeeHistory'
type MockEndpointInterface_GetFeeHistory_Call struct {
	*mock.Call
}

// GetFeeHistory is a helper method to define mock.On call
//   - payload1
func (_e *MockEndpointInterface_Expecter) GetFeeHistory(payload1 interface{}) *MockEndpointInterface_GetFeeHistory_Call {
	return &MockEndpointInterface_GetFeeHistory_Call{Call: _e.mock.On("GetFeeHistory", payload1)}
}

func (_c *MockEndpointInterface_GetFeeHistory_Call) Run(run func(payload1 payload.Payload)) *MockEndpointInterface_GetFeeHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(payload.Payload))
	})
	return _c
}

func (_c *MockEndpointInterface_GetFeeHistory_Call) Return(result *feehistory.Result, err error) *MockEndpointInterface_GetFeeHistory_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockEndpointInterface_GetFeeHistory_Call) RunAndReturn(run func(payload1 payload.Payload) (*feehistory.Result, error)) *MockEndpointInterface_GetFeeHistory_Call {
	_c.Call.Return(run)
	return _c
}
